version: "3"
services:

  wp-db:

    image: "postgres"

    container_name: "petshop_application"

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=petshopdb

    ports:
      - "5432:5432"